/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MasterAdminRouteImport } from './routes/master-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BloqueioRouteImport } from './routes/bloqueio'
import { Route as AceitarConviteRouteImport } from './routes/aceitar-convite'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppEquipeRouteImport } from './routes/_app/equipe'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppPacientesIndexRouteImport } from './routes/_app/pacientes.index'
import { Route as AppPacientesIdRouteImport } from './routes/_app/pacientes.$id'

const MasterAdminRoute = MasterAdminRouteImport.update({
  id: '/master-admin',
  path: '/master-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BloqueioRoute = BloqueioRouteImport.update({
  id: '/bloqueio',
  path: '/bloqueio',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteRoute = AceitarConviteRouteImport.update({
  id: '/aceitar-convite',
  path: '/aceitar-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesIndexRoute = AppPacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesIdRoute = AppPacientesIdRouteImport.update({
  id: '/pacientes/$id',
  path: '/pacientes/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/bloqueio': typeof BloqueioRoute
  '/login': typeof LoginRoute
  '/master-admin': typeof MasterAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/equipe': typeof AppEquipeRoute
  '/pacientes/$id': typeof AppPacientesIdRoute
  '/pacientes/': typeof AppPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/bloqueio': typeof BloqueioRoute
  '/login': typeof LoginRoute
  '/master-admin': typeof MasterAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/equipe': typeof AppEquipeRoute
  '/pacientes/$id': typeof AppPacientesIdRoute
  '/pacientes': typeof AppPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/aceitar-convite': typeof AceitarConviteRoute
  '/bloqueio': typeof BloqueioRoute
  '/login': typeof LoginRoute
  '/master-admin': typeof MasterAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/equipe': typeof AppEquipeRoute
  '/_app/pacientes/$id': typeof AppPacientesIdRoute
  '/_app/pacientes/': typeof AppPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceitar-convite'
    | '/bloqueio'
    | '/login'
    | '/master-admin'
    | '/dashboard'
    | '/equipe'
    | '/pacientes/$id'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aceitar-convite'
    | '/bloqueio'
    | '/login'
    | '/master-admin'
    | '/dashboard'
    | '/equipe'
    | '/pacientes/$id'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/aceitar-convite'
    | '/bloqueio'
    | '/login'
    | '/master-admin'
    | '/_app/dashboard'
    | '/_app/equipe'
    | '/_app/pacientes/$id'
    | '/_app/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AceitarConviteRoute: typeof AceitarConviteRoute
  BloqueioRoute: typeof BloqueioRoute
  LoginRoute: typeof LoginRoute
  MasterAdminRoute: typeof MasterAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/master-admin': {
      id: '/master-admin'
      path: '/master-admin'
      fullPath: '/master-admin'
      preLoaderRoute: typeof MasterAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloqueio': {
      id: '/bloqueio'
      path: '/bloqueio'
      fullPath: '/bloqueio'
      preLoaderRoute: typeof BloqueioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite': {
      id: '/aceitar-convite'
      path: '/aceitar-convite'
      fullPath: '/aceitar-convite'
      preLoaderRoute: typeof AceitarConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/equipe': {
      id: '/_app/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/': {
      id: '/_app/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AppPacientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/$id': {
      id: '/_app/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof AppPacientesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppPacientesIdRoute: typeof AppPacientesIdRoute
  AppPacientesIndexRoute: typeof AppPacientesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppPacientesIdRoute: AppPacientesIdRoute,
  AppPacientesIndexRoute: AppPacientesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AceitarConviteRoute: AceitarConviteRoute,
  BloqueioRoute: BloqueioRoute,
  LoginRoute: LoginRoute,
  MasterAdminRoute: MasterAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
